### PR TITLE
Skip lockdown document root

### PR DESCRIPTION
**Pull request by tmatsuo**
It's based on #377 

@jaitaiwan FYI

I'll surface this up to the runtime builder with another PR

### CODE REVIEW

**Comment by jaitaiwan** [comment]
Thanks @tmatsuo should I close the original PR?

**Comment by tmatsuo** [comment]
@jaitaiwan Yeah feel free to close the original one

**Comment by jaitaiwan** [comment]
@tmatsuo no worries and I'll also just not my explicit consent for the CLA

**Comment by tmatsuo** [comment]
@jaitaiwan Sorry, but what do you mean by "I'll also just not my explicit consent for the CLA"?

**Comment by tmatsuo** [comment]
@jaitaiwan Probably it's a typo of `note`

We read it as
"I'll also just note my explicit consent for the CLA"

and merge this

**Comment by tmatsuo** [comment]
Thanks @jaitaiwan

**Comment by jaitaiwan** [comment]
Thanks @tmatsuo that's exactly what I meant

**Pull request merged**
