### PR TITLE
Added ext-bcmath to the test app dependency.

### LINKED ISSUE #112: Add a test for build time ini scan
See #109

### PR DESCRIPTION
**Pull request by tmatsuo**
Also removed composer.lock so that composer needs to refer to composer.json.

fixes #112

### CODE REVIEW

**Comment by tmatsuo** [comment]
@cedricziel FYI

**Comment by cedricziel** [comment]
Thank you for covering my back! :)

LGTM

**Comment by tmatsuo** [comment]
@bshaffer This change makes sure that the php.ini in the project root directory works during the build.

**Comment by bshaffer** [comment]
LGTM, although I wish the test was more explicit

**Comment by tmatsuo** [comment]
@bshaffer merged, but pull request is welcome :)

**Pull request merged**
