### PR TITLE
Allow long requests by default.

### PR DESCRIPTION
**Pull request by tmatsuo**
Also fixes a bug about wrong nginx.conf path.

### CODE REVIEW

**Comment by tmatsuo** [comment]
The test for long running request was failing because on travis, guzzle uses fopen and the default_socket_timeout configuration (default 60 seconds) kicks in. I added a configuration change in the test code and let's see if it passes.

**Comment by bshaffer** [comment]
LGTM!

**Comment by tmatsuo** [comment]
I'll let you know once it's uploaded to prod

**Comment by tmatsuo** [comment]
It's uploaded

**Comment by bshaffer** [comment]
woohoo! I'll check it out now.

**Comment by bshaffer** [comment]
it worked!

**Pull request merged**
