### PR TITLE
Use php-cs-fixer 1.11.3

### PR DESCRIPTION
**Pull request by tmatsuo**

### CODE REVIEW

**Comment by tmatsuo** [comment]
I needed to use php-cs-fixer 1.11.3 due to the old version of PHP on our jenkins server.
Also needed to use --prefer-lowest to create the composer.lock file for the same reason.

**Comment by bshaffer** [comment]
Why can't we just use composer to install the required version? I don't see the advantage with this change.

**Comment by bshaffer** [comment]
i.e just use:
```php
"friendsofphp/php-cs-fixer": "1.11.3",
```

from [this tag](https://github.com/FriendsOfPHP/PHP-CS-Fixer/tree/v1.11.3)

**Comment by tmatsuo** [comment]
Yeah, that works too

**Comment by tmatsuo** [comment]
@bshaffer PTAL

**Comment by bshaffer** [comment]
LGTM

**Pull request merged**
