### PR TITLE
Upgraded to PHP 7.0.1.

### LINKED ISSUE #32: Upgrade to PHP 7.0.1

### PR DESCRIPTION
**Pull request by tmatsuo**
Fixes #32

### CODE REVIEW

**Comment by JustinBeckwith** [comment]
LGTM

**Comment by bshaffer** [comment]
Is this going to be necessary with every minor version update? We should consider automating this.

**Comment by tmatsuo** [comment]
Re: automation
That's great. Any ideas for automation are welcome :)

**Comment by tmatsuo** [comment]
Ouch, the e2e tests succeeded but it should fail because of the gcloud error.

**Comment by tmatsuo** [comment]
Investigating

**Comment by tmatsuo** [comment]
I can not reproduce this. Only explanation is that the previous run of the test was canceled, or it failed to delete the version and the test accessed to that version. Maybe I should add unique string to the version number.

**Comment by tmatsuo** [comment]
Tests are truly green (finally). I'm going to merge this. Please let me know if you have any concerns.

**Pull request merged**
