### PR TITLE
Upgrade to PHP 5.6.26 and 7.0.10.

### PR DESCRIPTION
**Pull request by tmatsuo**
Also cleaning up the installation processes for some extensions

### CODE REVIEW

**Comment by JustinBeckwith** [comment]
LGTM

**Comment by tmatsuo** [comment]
Thanks @JustinBeckwith

**Comment by tmatsuo** [comment]
Pushed to:
gcr.io/google_appengine/php:2016-08-19_23_57
gcr.io/google_appengine/php:staging

**Comment by tmatsuo** [comment]
Also pushed to gcr.io/google_appengine/php:latest

**Comment by bshaffer** [comment]
late LGTM

**Pull request merged**
