### PR TITLE
[BUGFIX] Composer install should not disable functions

### LINKED ISSUE #15: Docker: Composer doesn't use supplied php.ini
The supplied composer runner doesnt respect the supplied php.ini which makes it really hard to run post-install scripts that utilize for example ``symfony/console`` to generate optimized autoloaders (example: Laravel 5.1)

```
[Symfony\Component\Process\Exception\RuntimeException]
The Process class relies on proc_open, which is not available on your PHP installation.
```

I see that you've disabled the function on purpose, but really they shouldnt be limited on the CLI for one-off commands.

From my point of view, there's multiple possible solutions to the problem:

1. use the supplied ``php.ini`` to allow save overrides
2. use another php.ini (for example ``php.cli.ini``) just for composer
3. use another ini setting on the cli
4. override the contained php.ini in the image

I know I can override the supplied ``php.ini`` - maybe just document it to make it easier for people who are not into docker very much?

### PR DESCRIPTION
**Pull request by cedricziel**
Adds a configuration directive to ``composer.sh`` to clear the disabled functions to
allow execution of composer post-install hooks that rely on native processes.

Closes #15

### CODE REVIEW

**Comment by cedricziel** [comment]
The build fails as the RC8 tar is not available anymore.

This is fixed by #16

**Comment by tmatsuo** [comment]
@cedricziel Alright. Let's merge #16 first. Then can you rebase?

**Comment by cedricziel** [comment]
Sure-as soon as it's in :)

**Comment by tmatsuo** [comment]
It's in now. Please rebase and push.

**Comment by cedricziel** [comment]
Done. I will rebase #18 straight away.

**Comment by tmatsuo** [comment]
Thanks! Merging :)

**Pull request merged**
