### PR TITLE
Made the composer verbose, bug fixes and refactoring tests.

### PR DESCRIPTION
**Pull request by tmatsuo**
Changes in this PR
- Removed --quiet flag for composer, so that users can see reason for failure
- Refactored the test so that now you can run the whole test suite locally too
```
scripts/run_test_suite.sh
```
- Stopped deploying the newly built image on travis
  - Instead you can do it locally by setting PHP_DOCKER_DEPLOY=true and run run_test_suite.sh
- Fixed several bugs in tests

### CODE REVIEW

**Comment by tmatsuo** [comment]
@sjlangley Can you take a look?

**Comment by sjlangley** [comment]
lgtm

**Comment by tmatsuo** [comment]
Thx!

**Comment by tmatsuo** [comment]
The new image uploaded :)

**Pull request merged**
