### PR TITLE
WIP; migrate tests to structure test framework

### PR DESCRIPTION
**Pull request by nkubala**
This is preliminary work toward moving the structure tests for the PHP runtime image over to the GCP runtimes structure test framework. This will require all runs of the tests outside of the top level build script to use the external run script for these tests (found [here](https://github.com/GoogleCloudPlatform/runtimes-common/blob/master/structure_tests/ext_run.sh)).

@tmatsuo

### CODE REVIEW

**Comment by tmatsuo** [comment]
@nkubala 
Sorry I haven't looked carefully, but are there any issues with the tests which are commented out?

**Comment by nkubala** [comment]
> Sorry I haven't looked carefully, but are there any issues with the tests which are commented out?

This is something that I was planning on asking about. These tests rely on the image actually being run first, since when the image is run the `entrypoint.sh` script carries out a number of tasks which affect the structure of the image. This technically makes them "integration tests", however I would argue that what's actually being tested is still within the realm of "structure test" since it still only examines the structure of the image.

As such, how do you feel about moving some of the things in the entrypoint script into the Dockerfile itself? Is there any specific reason for creating config files, etc in an entrypoint script rather than just doing that when the image is built?

**Comment by tmatsuo** [comment]
@nkubala We're doing dynamic configuration based on the environment variable, which are not available at the build time. I'm open to other options, like moving those parts to the runtime builder etc.

**Comment by nkubala** [comment]
Hmm ok. Why aren't the env vars available at build time? When do those get set? In general my vote would be to try and move this config generation out of the entrypoint, and have it done prior to the image actually being run (if it's at all possible)

**Comment by tmatsuo** [comment]
@nkubala Unfortunately it's not possible now.

**Comment by tmatsuo** [comment]
@nkubala 

Did those test pass? If so can you enable them again?
Os should we add an integration test step in the `cloudbuild.yaml`?

**Comment by nkubala** [comment]
@tmatsuo as per our discussion, I'm going to wait on this until the integration testing framework is finished. Since most of the php structure tests require the container to actually be started before they can pass, we may need to just special case them as "integration" tests in the sense that an application built on top of the image will be deployed before the tests are run.

Given that some of the other tests for this runtime are outside of the scope of "standard" integration tests (more information on what that means to come soon), I'm perfectly fine with adding another cloudbuild step that deploys a sample application built on top of a newly built php runtime image and runs tests against that application. This would be an alternative (or a compliment to) running these tests through external CI such as Travis.

**Comment by tmatsuo** [comment]
I needed to make the change in the last commit for the build to succeed
(The build on CircleCI succeeded because it didn't use the cloudbuild at all)

**Comment by tmatsuo** [comment]
The commits are merged with #164

**Pull request closed without merging**
