### PR TITLE
Added /app to the --with-config-file-scan-dir option.

### PR DESCRIPTION
**Pull request by tmatsuo**
This is intentionally not using the environment variable.

To change the `APP_DIR` env var, first you need to change it in our PHP
binaries, upload those packages, then change it in
`php-nginx/Dockerfile`.

### CODE REVIEW

**Comment by tmatsuo** [comment]
@bshaffer 

Can you take a look? It turned out that we need to add /app to the config scan dir anyways, especially when we run composer install for users.

**Comment by tmatsuo** [comment]
We run `composer install` way before we copy the file. With the current design, we need to delay copying because we need to refer to the environment variable to determine which file to copy. When we run `composer install`, it is better to have `/app` as a scan dir.

I think we can do better when we move to the builder model, but now I think we need this

**Comment by tmatsuo** [comment]
Also, the original build script used to have ${APP_DIR} as the scan dir, so it's actually safe to add

**Comment by bshaffer** [comment]
But this means other `*.ini` files in that directory will be parsed as php config files, but we should only parse `php.ini`.

**Comment by tmatsuo** [comment]
@bshaffer 

Again, this is an old behavior and needed to migrate to debian package model. We can fix that sub optimal situation when we moved to the builder model

**Pull request merged**
