### PR TITLE
removes COMPOSER_CMD

### PR DESCRIPTION
**Pull request by bshaffer**
addendum to #142 - misc code cleanup

### CODE REVIEW

**Comment by tmatsuo** [comment]
I'm just curious. Why this is better?

**Comment by bshaffer** [comment]
The only reason for `$COMPOSER_CMD` was because the command was so long at the time (spanning ~10 lines) that it was more readable to set a variable. This is no longer the case, so removing a level of indirection (i.e. setting a variable and calling the variable) is more readable.

**Comment by tmatsuo** [comment]
There is still another trivial but good reason for having a variable. It's used twice. I wouldn't mind keeping the variable.

**Comment by bshaffer** [comment]
Then we should use it twice [here](https://github.com/GoogleCloudPlatform/php-docker/blob/master/php-nginx/composer.sh#L56), and set `${APP_DIR}/composer.json` to `$COMPOSER_JSON`. I don't think using something twice is a good reason to set a variable. The trade of indirection for code reuse is not always worth it.

**Comment by tmatsuo** [comment]
Those 2 calls and the assignment are very close in the script. It's not difficult to read at all.

**Comment by bshaffer** [comment]
It's not hard to read as is, but it's easier to read without it. Someone scanning the file doesn't know what `COMPOSER_CMD` is.  It's a nit, but this way is cleaner. Why have a variable you don't need?

**Comment by tmatsuo** [comment]
LGTM let's merge this after the test passes.

**Comment by bshaffer** [comment]
Thanks! I know it's a nit, but I am glad we merged it!

**Pull request merged**
