### PR TITLE
Travis test and documentation fixes

### PR DESCRIPTION
**Pull request by deustis**
- Updates TRAVIS.md instructions
- Adds a missing sudo to gcloud components update.
- Removes the deprecated "-f" flag from docker push commands.
- Adds the requires "--" separator to gcloud docker commands.
- Adds an error message when the gRPC to PubSub fails.

### CODE REVIEW

**Comment by bshaffer** [comment]
This all seems good to me! @tmatsuo ?

**Comment by tmatsuo** [comment]
Oh yes we migrated the test to circleci. Let's make sure the test runs on circleci too.

**Comment by deustis** [comment]
It's reporting failure on run_test_suite.sh, but I'm not sure what it's
trying to tell me. Any hints?:
https://circleci.com/gh/GoogleCloudPlatform/php-docker/101#tests/containers/0

**Comment by deustis** [comment]
Never mind, fixed. (It was a whitespace indent issue)

**Comment by deustis** [comment]
All passing now

**Comment by tmatsuo** [comment]
On circleci, e2e test is not running because there is no credentials file (it is expected because the PR is coming from other repo), but other tests are passing.

Thanks!

**Comment by tmatsuo** [comment]
The test succeeded for the pull request and failed with a push. It says:

> Error response from daemon: Conflict: Tag gcr.io/php-mvm-a/php-nginx:circle-105 is already set to image fad505991773, if you want to replace it, please use -f option

@deustis 
WDYT?

**Comment by deustis** [comment]
-f was deprecated in Docker 1.10 and removed in Docker 1.12:
https://docs.docker.com/engine/deprecated/

Maybe docker client needs to be updated in Circle CI tests?

**Comment by tmatsuo** [comment]
@deustis We're just using pre-installed docker on Circle CI. I will add `-f` on CircleCI for a temporary workaround.

**Comment by deustis** [comment]
@tmatsuo, ok. Just so you are aware, the -f does cause failures on Travis CI:

```
+docker tag -f gcr.io/deustis-php-docker/php-base:test php-base
unknown shorthand flag: 'f' in -f
See 'docker tag --help'.
```

**Pull request merged**
