### PR TITLE
Do not set HTTP_PROXY environment variable.

### PR DESCRIPTION
**Pull request by tmatsuo**

### CODE REVIEW

**Comment by tmatsuo** [comment]
I will add the test in the later CL

**Comment by broady** [comment]
LGTM

```
Nginx/FastCGI
Use this to block the header from being passed on to PHP-FPM, PHP-PM etc.

fastcgi_param HTTP_PROXY "";
In FastCGI configurations, PHP is vulnerable (but many other languages that use Nginx FastCGI are not).
```

**Comment by bshaffer** [comment]
This looks great

**Comment by cedricziel** [comment]
Great!

**Comment by tmatsuo** [comment]
FYI, it's deployed to everywhere in prod

**Pull request merged**
