### PR TITLE
Changed the file owner to root.www-data.

### LINKED ISSUE #75: Application files should be owned by root
Now we have the following in the `Dockerfile`:
```
ONBUILD RUN chown -R www-data.www-data $APP_DIR
```
It should be root.www-data so that php can not override any files.

### PR DESCRIPTION
**Pull request by tmatsuo**
Fixes #75

### CODE REVIEW

**Comment by bshaffer** [comment]
Looks good, although symfony will need to write the cache, so this change will break [this](https://github.com/GoogleCloudPlatform/php-docs-samples/blob/master/managed_vms/symfony/Dockerfile#L9)

**Comment by tmatsuo** [comment]
Yes, probably you need g+w?

**Comment by cedricziel** [comment]
In a derived image I use with symfony I needed to completely reset the file modes and ownerships to `www-data` + the umask (to 002) of the fpm process to have have a stable experience.

**Comment by tmatsuo** [comment]
@cedricziel alright, can you share your Dockerfile?

**Comment by tmatsuo** [comment]
Restarted the travis build

**Comment by tmatsuo** [comment]
Yeah it may break some apps. Do you mind if I submit this and push the latest image (it will happen automatically)?

**Comment by tmatsuo** [comment]
Ok, I would go ahead and merge this.

**Pull request merged**
