### PR TITLE
Upgrade to nginx-1.9.12.

### PR DESCRIPTION
**Pull request by tmatsuo**
Just talked with nginx guys and they recommend that we use mainline.

### CODE REVIEW

**Comment by tmatsuo** [comment]
The test is failing when trying to install semver with a memory error. I'll add some options to prevent it in another PR.

**Comment by bshaffer** [comment]
LGTM once tests pass!

**Comment by tmatsuo** [comment]
Alright, merging this.

**Comment by bshaffer** [comment]
:clap:

**Comment by tmatsuo** [comment]
Thanks! The image is pushed to production.

**Pull request merged**
