### PR TITLE
Stopped removing the vendor dir in composer.sh

### PR DESCRIPTION
**Pull request by tmatsuo**

### CODE REVIEW

**Comment by bshaffer** [comment]
This is a BC-breaking change, so it deserves some justification. Is https://github.com/docker/docker/issues/6047 no longer an issue?

**Comment by tmatsuo** [comment]
I added tests to make sure it's safe. Do you have particular concerns?

**Comment by tmatsuo** [comment]
And also we're going to put this image as `staging`, so that we can have enough time to test it before releasing it.

**Comment by bshaffer** [comment]
I mean I want to know why the decision was made

**Comment by tmatsuo** [comment]
@bshaffer Now we have decent test cases and release process so that we can put a new image as `staging`. Also cloudbuild environment keeps updating Docker versions. So I think it's a good time to do that.

**Comment by tmatsuo** [comment]
@bshaffer JFYI, the image is now at `gcr.io/google_appengine/php:staging`.

**Comment by tmatsuo** [comment]
Unfortunately I'm seeing an error during the build process of the application.

The example log is like this:

```
Step 1 : COPY . $APP_DIR
DEBUG: Operation [operations/build/google.com:php-bot/OGYxODM0ZjktNTUxNi00MTQxLTk5OGYtZWRlOTY0YzBjZWM0] not complete. Waiting 1s.
DEBUG: Reading GCS logfile: 206 (read 1350 bytes)
Step 1 : RUN chown -R www-data.www-data $APP_DIR
 ---> Running in 9852bf443d20
Step 1 : RUN /composer.sh
 ---> Running in 83051ef460ce
+ DEFAULT_PHP_VERSION=5.6
+ '[' -f /app/composer.json ']'
+ CMD='php /tmp/detect_php_version.php /app/composer.json'
++ su www-data -c 'php /tmp/detect_php_version.php /app/composer.json'
+ PHP_VERSION=
+ rm -rf /tmp/vendor /tmp/detect_php_version.php /tmp/composer.json /tmp/composer.lock
+ '[' '' '!=' 7.0 ']'
+ '[' '' '!=' 5.6 ']'
+ cat
There is no PHP runtime version specified in composer.json, or we don't support the version you specified. Google App Engine uses the latest stable version of PHP 
by default. We recommend pinning your PHP version by running:

composer require php ~5.6

Using PHP version 5.6.x...
+ PHP_VERSION=5.6
+ '[' 5.6 == 7.0 ']'
+ '[' 5.6 == 5.6 ']'
+ rm /opt/php
+ ln -sf /opt/php56 /opt/php
+ COMPOSER_GITHUB_OAUTH_TOKEN=
+ [[ -n '' ]]
+ unset COMPOSER_GITHUB_OAUTH_TOKEN
+ cd /app
+ su www-data -c 'php /usr/local/bin/composer           install           --no-scripts           --no-dev           --prefer-dist           --optimize-autoloader  
         --no-interaction           --no-ansi           --no-progress'
DEBUG: Operation [operations/build/google.com:php-bot/OGYxODM0ZjktNTUxNi00MTQxLTk5OGYtZWRlOTY0YzBjZWM0] not complete. Waiting 1s.
DEBUG: Reading GCS logfile: 206 (read 540 bytes)
Loading composer repositories with package information
Installing dependencies from lock file

                                                                                 
  [RuntimeException]                                                             
  /app/vendor/google/appengine-php-sdk does not exist and could not be created.
```

I'm still now sure why our test case could not catch this error, but I'm rolling back this change for now.

**Pull request merged**
