### PR TITLE
Use gcloud preview app versions delete.

### LINKED ISSUE #107: e2e test warns
WARNING: This command is deprecated. Please use `gcloud preview app versions delete` instead.

### PR DESCRIPTION
**Pull request by tmatsuo**
fixes #107

### CODE REVIEW

**Comment by tmatsuo** [comment]
@bshaffer The small change is just following the gcloud sdk change.

**Comment by bshaffer** [comment]
LGTM

**Comment by bshaffer** [comment]
Although I wouldn't mind using `sprintf` for readability:

```php
$cmd = sprintf(
    'gcloud -q preview app versions delete --service default --project %s %s',
    getenv(self::PROJECT_ENV),
    getenv(self::VERSION_ENV)
);
exec($cmd);
```

**Comment by tmatsuo** [comment]
@bshaffer Good sugestion, will do

**Comment by tmatsuo** [comment]
Done, unfortunately the build will fail until #119 is merged, so I stopped the build

**Comment by tmatsuo** [comment]
Alright, restarted the build

**Comment by tmatsuo** [comment]
Merging

**Pull request merged**
