### PR TITLE
Upgrade to nginx-1.8.1.

### PR DESCRIPTION
**Pull request by tmatsuo**
@JustinBeckwith @bshaffer Can you take a quick look? It's for security update.

### CODE REVIEW

**Comment by JustinBeckwith** [comment]
LGTM

**Comment by cedricziel** [comment]
:+1:

**Comment by tmatsuo** [comment]
Thanks, will merge once the tests pass.

**Comment by tmatsuo** [comment]
The new image uploaded. @cedricziel Please re-deploy the app if you are concerned about this.

**Pull request merged**
